import { useNavigate } from "react-router-dom";
import { useAuth } from "@/contexts/AuthContext";
import { Button } from "@/components/ui/button";
import { Plane, Sparkles, Pencil, BookmarkCheck, ArrowRight, MapPin, Clock } from "lucide-react";

const LandingPage = () => {
  const { user } = useAuth();
  const navigate = useNavigate();

  const handleCTA = () => {
    navigate(user ? "/create-trip" : "/auth");
  };

  return (
    <div className="min-h-screen bg-background">
      {/* Hero */}
      <header className="relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-br from-primary/5 via-transparent to-accent/5" />
        <nav className="container mx-auto flex items-center justify-between px-4 py-5">
          <div className="flex items-center gap-2 font-bold text-xl">
            <Plane className="h-6 w-6 text-primary" />
            <span>TripAI</span>
          </div>
          <Button variant="ghost" size="sm" onClick={() => navigate("/auth")}>
            {user ? "Dashboard" : "Sign In"}
          </Button>
        </nav>

        <div className="container mx-auto px-4 py-20 md:py-32 text-center relative">
          <div className="inline-flex items-center gap-2 rounded-full border bg-card px-4 py-1.5 text-xs font-medium text-muted-foreground mb-6">
            <Sparkles className="h-3.5 w-3.5 text-accent" />
            AI-Powered Trip Planning
          </div>
          <h1 className="text-4xl md:text-6xl font-extrabold tracking-tight max-w-3xl mx-auto leading-tight">
            Plan Your Perfect Trip{" "}
            <span className="text-primary">in Seconds</span>
          </h1>
          <p className="mt-5 text-lg text-muted-foreground max-w-xl mx-auto">
            Tell AI where you want to go. Get a complete, editable day-by-day itinerary instantly.
          </p>
          <Button size="lg" onClick={handleCTA} className="mt-8 text-base px-8 active:scale-95 transition-transform">
            Start Planning <ArrowRight className="ml-2 h-4 w-4" />
          </Button>
        </div>
      </header>

      {/* Features */}
      <section className="container mx-auto px-4 py-16">
        <div className="grid md:grid-cols-3 gap-6 max-w-4xl mx-auto">
          {[
            { icon: Sparkles, title: "AI-Powered", desc: "Describe your dream trip and get a structured itinerary generated by AI in seconds." },
            { icon: Pencil, title: "Fully Customizable", desc: "Edit activities, drag to reorder, add your own stops — make it truly yours." },
            { icon: BookmarkCheck, title: "Save & Manage", desc: "Save trips to your dashboard. Access and edit them anytime, anywhere." },
          ].map((f, i) => (
            <div key={i} className="rounded-2xl border bg-card p-6 text-center hover:shadow-md transition-shadow duration-200">
              <div className="mx-auto mb-4 flex h-12 w-12 items-center justify-center rounded-xl bg-primary/10">
                <f.icon className="h-6 w-6 text-primary" />
              </div>
              <h3 className="font-semibold mb-2">{f.title}</h3>
              <p className="text-sm text-muted-foreground">{f.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Sample itinerary */}
      <section className="container mx-auto px-4 pb-16">
        <div className="max-w-2xl mx-auto rounded-2xl border bg-card p-6 shadow-sm">
          <div className="flex items-center gap-2 mb-4">
            <span className="text-2xl">🏖️</span>
            <div>
              <h3 className="font-bold">Goa Beach Getaway</h3>
              <p className="text-xs text-muted-foreground">Goa, India · 2 Days</p>
            </div>
          </div>
          <div className="space-y-3">
            {[
              { time: "09:00 – 11:00", name: "Baga Beach Morning", loc: "Baga Beach" },
              { time: "12:00 – 13:30", name: "Seafood Lunch at Britto's", loc: "Britto's, Baga" },
              { time: "15:00 – 17:00", name: "Old Goa Heritage Walk", loc: "Basilica of Bom Jesus" },
            ].map((a, i) => (
              <div key={i} className="flex gap-3 items-start text-sm rounded-lg bg-secondary/50 p-3">
                <div className="flex items-center gap-1 text-xs text-muted-foreground shrink-0">
                  <Clock className="h-3 w-3" />
                  {a.time}
                </div>
                <div>
                  <p className="font-medium">{a.name}</p>
                  <p className="text-xs text-muted-foreground flex items-center gap-1">
                    <MapPin className="h-3 w-3" /> {a.loc}
                  </p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t py-6 text-center text-xs text-muted-foreground">
        Built at AIAP Hackathon
      </footer>
    </div>
  );
};

export default LandingPage;
