/ → LandingPage (public)
/auth → AuthPage (public; redirect to /dashboard if already authenticated)
/create-trip → CreateTripPage (protected)
/trip/:id → ItineraryPage (protected)
/dashboard → DashboardPage (protected)
